sudo virt-install\
		--name mephisto\
		--ram=4096\
		--vcpus=1,maxvcpus=4\
		--cpu host\
		--hvm\
		--boot uefi\
		--disk path=/var/lib/libvirt/images/image_mephisto,size=40,pool=images\
		--cdrom /var/lib/libvirt/isos/arch.iso\
		--network bridge=br0\
		--graphics vnc,port=5902
